[package]
name = "ws_client"
version = "0.1.0"
edition = "2021"

[dependencies]
base64 = "0.22.1"
bytes = "1.10.1"
criterion = "0.7.0"
env_logger = "0.11.8"
httparse = "=1.8.0"
log = "0.4.27"
native-tls = "0.2.14"
rand = "0.9.1"
sha1 = "0.10.6"
thiserror = "2.0.12"
tungstenite = "0.20.0"
url = "2.5.4"

[[example]]
name = "blocking"

[[example]]
name = "nonblocking"